project:
  type: book

book:
  title: "My Book"
  author: "Nikita Book"
  date: "04/20/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - part: A Part
      chapters:
        - summary.qmd
        - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
